Repository Gray-Pants/BE, pull requests merged in 2024-07, with the labels that each got.

#5 [FEAT] ApiResponseUtil class 구현
  src/main/java/com/poku/graypants/global/util/ApiResponseUtil.java
Labels: :sparkles: feat

#9 [FEAT] Exception 처리 로직 구현
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/java/com/poku/graypants/global/exception/GrayPantsException.java
  src/main/java/com/poku/graypants/global/exception/GrayPantsExceptionHandler.java
Labels: :sparkles: feat

#11 [FEAT] OAuth2 로그인 로직 구현
  .gitignore
  build.gradle
  src/main/java/com/poku/graypants/GrayPantsApplication.java
  src/main/java/com/poku/graypants/domain/auth/application/OAuthService.java
  src/main/java/com/poku/graypants/domain/auth/persistence/OAuth.java
  src/main/java/com/poku/graypants/domain/auth/persistence/OAuthRepository.java
  src/main/java/com/poku/graypants/domain/user/application/UserService.java
  src/main/java/com/poku/graypants/domain/user/persistence/User.java
  src/main/java/com/poku/graypants/domain/user/persistence/UserRepository.java
  src/main/java/com/poku/graypants/domain/user/web/UserController.java
  src/main/java/com/poku/graypants/global/config/filter/TokenAuthenticationFilter.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuth2SuccessHandler.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuth2UserCustomService.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuthSecurityConfig.java
  src/main/java/com/poku/graypants/global/config/oauth/PrincipalDetails.java
  src/main/java/com/poku/graypants/global/config/oauth/info/GoogleUserInfo.java
  src/main/java/com/poku/graypants/global/config/oauth/info/KakaoUserInfo.java
  src/main/java/com/poku/graypants/global/config/oauth/info/NaverUserInfo.java
  src/main/java/com/poku/graypants/global/config/oauth/info/OAuth2UserInfo.java
  src/main/java/com/poku/graypants/global/config/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/poku/graypants/global/jwt/JwtProperties.java
  src/main/java/com/poku/graypants/global/jwt/JwtProvider.java
  src/main/java/com/poku/graypants/global/util/CookieUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: feat

#10 [FEAT] 상품, 카테고리, 스토어 엔티티 생성
  src/main/java/com/poku/graypants/domain/product/persistence/Category.java
  src/main/java/com/poku/graypants/domain/product/persistence/Item.java
  src/main/java/com/poku/graypants/domain/product/persistence/ItemPhoto.java
  src/main/java/com/poku/graypants/domain/product/persistence/OrderItem.java
  src/main/java/com/poku/graypants/domain/product/persistence/OrderItemStatus.java
  src/main/java/com/poku/graypants/domain/product/persistence/Store.java
Labels: :sparkles: feat

#17 [Feat] 상품 CRUD 및 QueryDSL 의존성 주입
  build.gradle
  src/main/java/com/poku/graypants/domain/auth/application/OAuthService.java
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemCreateDto.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemRequestDto.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemResponseDto.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemUpdateDto.java
  src/main/java/com/poku/graypants/domain/item/persistence/Category.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemPhoto.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepository.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepositoryCustom.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepositoryCustomImpl.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/domain/store/persistence/StoreRepository.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
Labels: :sparkles: feat

#18 [HOTFIX] fix ItemRepositoryCustomImpl
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepositoryCustomImpl.java
  src/main/java/com/poku/graypants/global/persistence/BaseTime.java
Labels: :bug: bug

#20 [Feat] BaseEntity class 생성 #6
  src/main/java/com/poku/graypants/GrayPantsApplication.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemResponseDto.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/order/persistence/Order.java
  src/main/java/com/poku/graypants/domain/order/persistence/OrderItem.java
  src/main/java/com/poku/graypants/domain/store/persistence/Store.java
  src/main/java/com/poku/graypants/global/entity/BaseTime.java
  src/main/java/com/poku/graypants/global/persistence/BaseTime.java
Labels: :sparkles: feat

#28 [Feat] 소셜로그인을 이용한 회원가입 후 찜하기 기능
  src/main/java/com/poku/graypants/domain/cart/application/CartService.java
  src/main/java/com/poku/graypants/domain/cart/application/dto/CartItemAddRequestDto.java
  src/main/java/com/poku/graypants/domain/cart/application/dto/CartItemUpdateRequestDto.java
  src/main/java/com/poku/graypants/domain/cart/persistence/Cart.java
  src/main/java/com/poku/graypants/domain/cart/persistence/CartItem.java
  src/main/java/com/poku/graypants/domain/cart/persistence/CartItemRepository.java
  src/main/java/com/poku/graypants/domain/cart/persistence/CartRepository.java
  src/main/java/com/poku/graypants/domain/cart/web/CartController.java
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemResponseDto.java
  src/main/java/com/poku/graypants/domain/item/persistence/Category.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemPhoto.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepository.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepositoryCustom.java
  src/main/java/com/poku/graypants/domain/like/application/LikeService.java
  src/main/java/com/poku/graypants/domain/like/application/dto/LikeRequestDto.java
  src/main/java/com/poku/graypants/domain/like/application/dto/LikeResponseDto.java
  src/main/java/com/poku/graypants/domain/like/persistence/Like.java
  src/main/java/com/poku/graypants/domain/like/persistence/LikeFactory.java
  src/main/java/com/poku/graypants/domain/like/persistence/LikeRepository.java
  src/main/java/com/poku/graypants/domain/like/web/LikeController.java
  src/main/java/com/poku/graypants/domain/order/persistence/OrderItem.java
  src/main/java/com/poku/graypants/domain/store/persistence/Store.java
  src/main/java/com/poku/graypants/domain/user/application/UserService.java
  src/main/java/com/poku/graypants/domain/user/persistence/User.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: :sparkles: feat

#32 feat: 스토어 회원가입 및 로그인 로직 구현
  src/main/java/com/poku/graypants/domain/auth/application/EmailAuthService.java
  src/main/java/com/poku/graypants/domain/auth/application/dto/EmailLoginRequestDto.java
  src/main/java/com/poku/graypants/domain/auth/application/dto/EmailSignupRequestDto.java
  src/main/java/com/poku/graypants/domain/auth/persistence/EmailAuthenticateAble.java
  src/main/java/com/poku/graypants/domain/auth/web/AuthController.java
  src/main/java/com/poku/graypants/domain/mail/application/MailService.java
  src/main/java/com/poku/graypants/domain/mail/application/dto/VerificationEmailSendRequestDto.java
  src/main/java/com/poku/graypants/domain/mail/application/dto/VerifyEmailRequestDto.java
  src/main/java/com/poku/graypants/domain/store/application/StoreService.java
  src/main/java/com/poku/graypants/domain/store/persistence/Store.java
  src/main/java/com/poku/graypants/domain/store/persistence/StoreRepository.java
  src/main/java/com/poku/graypants/domain/user/application/UserService.java
  src/main/java/com/poku/graypants/domain/user/persistence/User.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/java/com/poku/graypants/global/jwt/JwtProvider.java
  src/main/java/com/poku/graypants/global/jwt/JwtService.java
Labels: :sparkles: feat

#36 [FEAT] 스웨거 도입 및 인가로직 삽입
  build.gradle
  src/main/java/com/poku/graypants/domain/auth/web/AuthController.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/domain/like/application/LikeService.java
  src/main/java/com/poku/graypants/domain/like/application/dto/LikeRequestDto.java
  src/main/java/com/poku/graypants/domain/like/web/LikeController.java
  src/main/java/com/poku/graypants/domain/mail/web/MailController.java
  src/main/java/com/poku/graypants/domain/user/web/UserController.java
  src/main/java/com/poku/graypants/global/config/oauth/CustomAccessDeniedHandler.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuthSecurityConfig.java
  src/main/java/com/poku/graypants/global/config/swagger/SwaggerConfig.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#35 [Feat] 상품이미지 업로드 로직 아마존 S3 연동
  build.gradle
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemCreateRequestDto.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemResponseDto.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemUpdateRequestDto.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemPhoto.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/domain/like/application/LikeService.java
  src/main/java/com/poku/graypants/global/config/img/S3ImgConfig.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#42 [Fix] item controller api
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuthSecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#41 [Feat] Order 및 OrderItem 로직 작성
  build.gradle
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/domain/like/application/LikeService.java
  src/main/java/com/poku/graypants/domain/like/web/LikeController.java
  src/main/java/com/poku/graypants/domain/order/application/OrderService.java
  src/main/java/com/poku/graypants/domain/order/application/OrderServiceImpl.java
  src/main/java/com/poku/graypants/domain/order/application/dto/OrderCreateRequestDto.java
  src/main/java/com/poku/graypants/domain/order/application/dto/OrderResponseDto.java
  src/main/java/com/poku/graypants/domain/order/application/dto/OrderUpdateRequestDto.java
  src/main/java/com/poku/graypants/domain/order/persistence/Order.java
  src/main/java/com/poku/graypants/domain/order/persistence/OrderRepository.java
  src/main/java/com/poku/graypants/domain/order/web/OrderController.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemService.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemServiceImpl.java
  src/main/java/com/poku/graypants/domain/orderItem/application/dto/OrderItemCreateRequestDto.java
  src/main/java/com/poku/graypants/domain/orderItem/application/dto/OrderItemResponseDto.java
  src/main/java/com/poku/graypants/domain/orderItem/application/dto/OrderItemUpdateRequestDto.java
  src/main/java/com/poku/graypants/domain/orderItem/persistence/OrderItem.java
  src/main/java/com/poku/graypants/domain/orderItem/persistence/OrderItemRepository.java
  src/main/java/com/poku/graypants/domain/store/application/StoreService.java
  src/main/java/com/poku/graypants/domain/user/application/UserService.java
  src/main/java/com/poku/graypants/domain/user/persistence/User.java
  src/main/java/com/poku/graypants/global/config/cache/CacheConfig.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuthSecurityConfig.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/java/com/poku/graypants/global/util/ApiResponseUtil.java
  src/test/java/com/poku/graypants/domain/order/persistence/OrderRepositoryTest.java
Labels: enhancement, :sparkles: feat

#44 [Feat] 리뷰와 관련된 CRUD 기능 개발
  src/main/java/com/poku/graypants/domain/auth/application/OAuthService.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/like/persistence/Like.java
  src/main/java/com/poku/graypants/domain/review/application/ReviewService.java
  src/main/java/com/poku/graypants/domain/review/application/dto/ReviewDTO.java
  src/main/java/com/poku/graypants/domain/review/application/dto/ReviewRequestDTO.java
  src/main/java/com/poku/graypants/domain/review/application/dto/ReviewResponseDTO.java
  src/main/java/com/poku/graypants/domain/review/persistence/Review.java
  src/main/java/com/poku/graypants/domain/review/persistence/ReviewRepository.java
  src/main/java/com/poku/graypants/domain/review/web/ReviewController.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
Labels: :sparkles: feat

#51 [Feat] 상품 목록 데이터 연동
  src/main/java/com/poku/graypants/domain/cart/application/CartService.java
  src/main/java/com/poku/graypants/domain/item/application/ItemDataService.java
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepository.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemServiceImpl.java
  src/main/java/com/poku/graypants/domain/store/application/StoreService.java
  src/main/java/com/poku/graypants/domain/store/web/StoreController.java
Labels: :sparkles: feat

#54 [FEAT] 유저 결제정보 가져오는 로직 구현
  src/main/java/com/poku/graypants/domain/order/application/OrderDataService.java
  src/main/java/com/poku/graypants/domain/order/application/OrderServiceImpl.java
  src/main/java/com/poku/graypants/domain/order/application/dto/OrderResponseDto.java
  src/main/java/com/poku/graypants/domain/order/persistence/Order.java
  src/main/java/com/poku/graypants/domain/order/persistence/OrderRepository.java
  src/main/java/com/poku/graypants/domain/order/web/OrderController.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemService.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemServiceImpl.java
  src/main/java/com/poku/graypants/domain/orderItem/application/dto/OrderItemResponseDto.java
  src/main/java/com/poku/graypants/domain/user/application/UserService.java
  src/main/java/com/poku/graypants/domain/user/web/UserController.java
Labels: :sparkles: feat

#60 [Feat] 아이템 정렬, 조회, 카테고리
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/persistence/Category.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepository.java
  src/main/java/com/poku/graypants/domain/item/persistence/ItemRepositoryCustomImpl.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/resources/application-s3.yml
  src/main/resources/data.sql
Labels: :sparkles: feat

#63 [Feat] 아이템 등록 시 스토어 로그인 정보 가져오기
  build.gradle
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/item/application/dto/ItemCreateRequestDto.java
  src/main/java/com/poku/graypants/domain/item/persistence/Category.java
  src/main/java/com/poku/graypants/domain/item/persistence/Item.java
  src/main/java/com/poku/graypants/domain/item/web/ItemController.java
  src/main/java/com/poku/graypants/domain/store/application/StoreService.java
Labels: :sparkles: feat

#65 [FEAT] 회원 주소 CRUD 구현
  src/main/java/com/poku/graypants/domain/addr/application/AddrService.java
  src/main/java/com/poku/graypants/domain/addr/application/Dto/AddrRequestDto.java
  src/main/java/com/poku/graypants/domain/addr/application/Dto/AddrResponseDto.java
  src/main/java/com/poku/graypants/domain/addr/persistence/AddrRepository.java
  src/main/java/com/poku/graypants/domain/addr/persistence/UserAddr.java
  src/main/java/com/poku/graypants/domain/addr/web/AddrController.java
  src/main/java/com/poku/graypants/domain/user/persistence/User.java
  src/main/java/com/poku/graypants/global/exception/ExceptionStatus.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#68 [FEAT] 회원 닉네임 변경 및 주소추가 기능, 내 주소 가져오는 기능 구현
  src/main/java/com/poku/graypants/domain/addr/application/AddrService.java
  src/main/java/com/poku/graypants/domain/addr/application/Dto/AddrRequestDto.java
  src/main/java/com/poku/graypants/domain/addr/application/Dto/AddrResponseDto.java
  src/main/java/com/poku/graypants/domain/user/application/UserDataService.java
  src/main/java/com/poku/graypants/domain/user/application/UserService.java
  src/main/java/com/poku/graypants/domain/user/application/dto/ChangeUserNameResponseDto.java
  src/main/java/com/poku/graypants/domain/user/application/dto/MemberInformationResponseDto.java
  src/main/java/com/poku/graypants/domain/user/persistence/User.java
  src/main/java/com/poku/graypants/domain/user/web/UserController.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: :sparkles: feat

#71 Feat 판매자 상품 목록 데이터 연동 코드 개발
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemDataService.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemServiceImpl.java
  src/main/java/com/poku/graypants/domain/orderItem/persistence/OrderItemRepository.java
  src/main/java/com/poku/graypants/domain/store/application/MyOrderItemsResponseDto.java
  src/main/java/com/poku/graypants/domain/store/application/StoreService.java
  src/main/java/com/poku/graypants/domain/store/web/StoreController.java
  src/main/java/com/poku/graypants/global/config/oauth/OAuthSecurityConfig.java
  src/main/java/com/poku/graypants/global/jwt/JwtService.java
Labels: :sparkles: feat

#70 FEAT: kakaoPay complete
  src/main/java/com/poku/graypants/domain/item/application/ItemService.java
  src/main/java/com/poku/graypants/domain/order/application/OrderService.java
  src/main/java/com/poku/graypants/domain/order/application/OrderServiceImpl.java
  src/main/java/com/poku/graypants/domain/order/application/dto/OrderCreateRequestDto.java
  src/main/java/com/poku/graypants/domain/order/persistence/Order.java
  src/main/java/com/poku/graypants/domain/order/web/OrderController.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemDataService.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemService.java
  src/main/java/com/poku/graypants/domain/orderItem/application/OrderItemServiceImpl.java
  src/main/java/com/poku/graypants/domain/orderItem/application/dto/OrderItemCreateRequestDto.java
  src/main/java/com/poku/graypants/domain/orderItem/persistence/OrderItem.java
  src/main/java/com/poku/graypants/domain/payments/application/KakaoPayService.java
  src/main/java/com/poku/graypants/domain/payments/persistence/dto/Amount.java
  src/main/java/com/poku/graypants/domain/payments/persistence/dto/KakaoPayApproveResponseDto.java
  src/main/java/com/poku/graypants/domain/payments/persistence/dto/KakaoPayClientReadyRequestDto.java
  src/main/java/com/poku/graypants/domain/payments/web/KakaoPayController.java
Labels: :sparkles: feat
